# https://readthedocs.org/projects/pyspod/builds/

version: 2

formats: all

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.14"

python:
   install:
     - path: .[docs]

sphinx:
   configuration: docs/source/conf.py
   fail_on_warning: true
